import {
	MAX_PREVIEW_DOM_COMMITS_PER_SECOND,
	MIN_PREVIEW_DOM_COMMITS_PER_SECOND,
	PREVIEW_DOM_COMMITS_STEP,
} from "card-preview/scheduling/previewSchedulingConfig";
import {
	parseNonNegativeInteger,
	parsePositiveInteger,
	parsePositiveNumber,
	parseTrimmedString,
} from "./settingDefinition";
import type { SettingDefinition } from "./settingDefinition";

export const PREVIEW_SETTING_DEFINITIONS: ReadonlyArray<SettingDefinition> = [
	{
		section: "cards",
		settingKey: "cardWidthPx",
		controlType: "text",
		translationKey: "cardWidth",
		descriptionKey: "cardWidthDesc",
		placeholder: "140",
		parse: (value) => parsePositiveInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "cards",
		settingKey: "cardHeightRatio",
		controlType: "text",
		translationKey: "cardHeightRatio",
		descriptionKey: "cardHeightRatioDesc",
		placeholder: "1.1",
		parse: (value) => parsePositiveNumber(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "cards",
		settingKey: "cardGapPx",
		controlType: "text",
		translationKey: "cardGap",
		descriptionKey: "cardGapDesc",
		placeholder: "12",
		parse: (value) => parseNonNegativeInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "cards",
		settingKey: "cardMaxColumns",
		controlType: "text",
		translationKey: "cardMaxColumns",
		descriptionKey: "cardMaxColumnsDesc",
		placeholder: "6",
		parse: (value) => parsePositiveInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "cards",
		settingKey: "previewScrollCommitsPerSecond",
		controlType: "slider",
		translationKey: "previewScrollSpeed",
		descriptionKey: "previewScrollSpeedDesc",
		min: MIN_PREVIEW_DOM_COMMITS_PER_SECOND,
		max: MAX_PREVIEW_DOM_COMMITS_PER_SECOND,
		step: PREVIEW_DOM_COMMITS_STEP,
	},
	{
		section: "cards",
		settingKey: "priorityFrontmatterKeysForImagePreview",
		controlType: "text",
		translationKey: "priorityFrontmatterKeysForImagePreview",
		descriptionKey: "priorityFrontmatterKeysForImagePreviewDesc",
		placeholder: "image, cover, thumbnail",
		parse: (value) => parseTrimmedString(value),
		format: (value) => (typeof value === "string" ? value : ""),
	},
	{
		section: "cards",
		settingKey: "priorityFrontmatterKeyForPreview",
		controlType: "text",
		translationKey: "priorityFrontmatterKeyForPreview",
		descriptionKey: "priorityFrontmatterKeyForPreviewDesc",
		placeholder: "description, summary",
		parse: (value) => parseTrimmedString(value),
		format: (value) => (typeof value === "string" ? value : ""),
	},
	{
		section: "cards",
		settingKey: "priorityFrontmatterKeyForTitle",
		controlType: "text",
		translationKey: "priorityFrontmatterKeyForTitle",
		descriptionKey: "priorityFrontmatterKeyForTitleDesc",
		placeholder: "title, name",
		parse: (value) => parseTrimmedString(value),
		format: (value) => (typeof value === "string" ? value : ""),
	},
];
