import { DEFAULT_PREVIEW_DOM_COMMITS_PER_SECOND } from "card-preview/scheduling/previewSchedulingConfig";
import {
	DEFAULT_CARD_GAP_PX,
	DEFAULT_CARD_HEIGHT_RATIO,
	DEFAULT_CARD_MAX_COLUMNS,
	DEFAULT_CARD_WIDTH_PX,
	DEFAULT_SECTION_MARGIN_BOTTOM_PX,
	type PluginSettings,
} from "./settings";

export const DEFAULT_SETTINGS: PluginSettings = {
	language: "en",
	displayMode: "editor-inline",
	useMergedLinksSection: false,
	dedupeCards: true,
	enableTagFeatures: true,
	showTagsSection: true,
	defaultVisibleLinkCount: 15,
	loadMoreLinkIncrement: 15,
	cardWidthPx: DEFAULT_CARD_WIDTH_PX,
	cardHeightRatio: DEFAULT_CARD_HEIGHT_RATIO,
	cardGapPx: DEFAULT_CARD_GAP_PX,
	cardMaxColumns: DEFAULT_CARD_MAX_COLUMNS,
	sectionMarginBottomPx: DEFAULT_SECTION_MARGIN_BOTTOM_PX,
	highlightOnOpen: true,
	highlightInPreviewOnHover: true,
	twoHopHeaderSortOrder: "appearance",
	lastUsedSortOption: "alphabetical",
	quickSortField1: "modified-date",
	quickSortField2: "none",
	previewMaxLines: 15,
	previewMaxChars: 500,
	previewVisualLineSafetyMargin: 0,
	previewScrollCommitsPerSecond: DEFAULT_PREVIEW_DOM_COMMITS_PER_SECOND,
	excludeAttachments: false,
	frontmatterKeyCreatedDate: "",
	frontmatterKeyModifiedDate: "",
	enableGlobalSearchTagModal: true,
	enableUnresolvedLinkModal: true,
	enableEmptyViewAllNotesInNewTab: true,
	pinBookmarkedToTopInAllNotes: true,
	enableUnresolvedLinkDecoration: true,
	experimentalCosenseTitleEditing: false,
	experimentalShadowDomCss: "",
	priorityFrontmatterKeysForImagePreview: "",
	priorityFrontmatterKeyForPreview: "",
	priorityFrontmatterKeyForTitle: "",
	enableContentSearch: false,
};
